//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DensityExpressionGrammar.g4 by ANTLR 4.6.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDensityExpressionGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class DensityExpressionGrammarBaseListener : IDensityExpressionGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompileUnit([NotNull] DensityExpressionGrammarParser.CompileUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.compileUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompileUnit([NotNull] DensityExpressionGrammarParser.CompileUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquation([NotNull] DensityExpressionGrammarParser.EquationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.equation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquation([NotNull] DensityExpressionGrammarParser.EquationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] DensityExpressionGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] DensityExpressionGrammarParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] DensityExpressionGrammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] DensityExpressionGrammarParser.TermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] DensityExpressionGrammarParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] DensityExpressionGrammarParser.FactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] DensityExpressionGrammarParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] DensityExpressionGrammarParser.AtomContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] DensityExpressionGrammarParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] DensityExpressionGrammarParser.NumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] DensityExpressionGrammarParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] DensityExpressionGrammarParser.VariableContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DensityExpressionGrammarParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelop([NotNull] DensityExpressionGrammarParser.RelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DensityExpressionGrammarParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelop([NotNull] DensityExpressionGrammarParser.RelopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
